#!/bin/bash

echo "==================================="
echo "Railway Deployment Instructions"
echo "==================================="
echo ""
echo "Since Railway CLI has path issues, please deploy using one of these methods:"
echo ""
echo "METHOD 1: GitHub Integration (Recommended)"
echo "-------------------------------------------"
echo "1. Create a new GitHub repository"
echo "2. Push this backend folder to the repo:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial backend commit'"
echo "   git remote add origin YOUR_GITHUB_REPO_URL"
echo "   git push -u origin main"
echo ""
echo "3. In Railway dashboard:"
echo "   - Go to your 'amiable-vision' project (personal workspace)"
echo "   - Click 'New Service' > 'GitHub Repo'"
echo "   - Select your repository"
echo "   - Railway will auto-deploy"
echo ""
echo "METHOD 2: Direct Upload via Dashboard"
echo "--------------------------------------"
echo "1. Go to https://railway.app/dashboard"
echo "2. Select your personal workspace (not Tandem)"
echo "3. Open the 'amiable-vision' project"
echo "4. Click 'New Service' > 'Empty Service'"
echo "5. Drag and drop the 'backend' folder"
echo "6. Railway will build and deploy"
echo ""
echo "ENVIRONMENT VARIABLES TO SET IN RAILWAY:"
echo "-----------------------------------------"
echo "1. Click on your deployed service"
echo "2. Go to 'Variables' tab"
echo "3. Add these variables:"
echo "   NODE_ENV=production"
echo "   ADMIN_KEY=<choose-a-secret-key>"
echo ""
echo "4. Connect to your Postgres database:"
echo "   - Click 'Add Variable Reference'"
echo "   - Select your 'respendit-illumination' database"
echo "   - Choose DATABASE_URL"
echo ""
echo "AFTER DEPLOYMENT:"
echo "-----------------"
echo "1. Copy your Railway service URL"
echo "2. Update line 629 in Lokesh.dc.html:"
echo "   Change 'https://your-backend.railway.app'"
echo "   To your actual Railway URL"
echo ""
echo "==================================="