#!/bin/bash

RAILWAY="/opt/homebrew/Cellar/railway/4.16.1/bin/railway"

echo "========================================="
echo "🚂 Railway Deployment Guide"
echo "========================================="
echo ""
echo "You're logged in as: Lokesh Kamanboina"
echo "Repository: https://github.com/kamanbo23/portfolio-backend"
echo ""
echo "Step 1: Link to Railway Project"
echo "--------------------------------"
echo "Run this command and select your project:"
echo ""
echo "cd '/Users/lokesh/Downloads/Personal web/backend'"
echo "$RAILWAY link"
echo ""
echo "When prompted:"
echo "  - Select: Personal workspace"
echo "  - Select: amiable-vision (your existing project)"
echo "  - Create new service: portfolio-backend"
echo ""
echo "Step 2: Deploy from GitHub"
echo "---------------------------"
echo "After linking, run:"
echo ""
echo "$RAILWAY service"
echo ""
echo "Then:"
echo "  - Select 'Connect GitHub repo'"
echo "  - Choose: kamanbo23/portfolio-backend"
echo ""
echo "Step 3: Set Environment Variables"
echo "----------------------------------"
echo "$RAILWAY variables set NODE_ENV=production"
echo "$RAILWAY variables set ADMIN_KEY=your-secret-key-here"
echo ""
echo "Step 4: Connect Database"
echo "-------------------------"
echo "In Railway dashboard:"
echo "  - Go to your service"
echo "  - Variables tab"
echo "  - Add Variable Reference"
echo "  - Select respendit-illumination"
echo "  - Choose DATABASE_URL"
echo ""
echo "Step 5: Deploy"
echo "---------------"
echo "$RAILWAY up"
echo ""
echo "========================================="
echo "Quick Commands (run in order):"
echo "========================================="
echo ""
echo "# 1. Link project"
echo "cd '/Users/lokesh/Downloads/Personal web/backend' && $RAILWAY link"
echo ""
echo "# 2. After linking, deploy"
echo "$RAILWAY up"
echo ""
echo "# 3. Open Railway dashboard"
echo "$RAILWAY open"
echo ""
echo "========================================="