#!/bin/bash

# GitHub CLI is installed at /tmp/gh_2.41.0_macOS_arm64/bin/gh
GH="/tmp/gh_2.41.0_macOS_arm64/bin/gh"

echo "========================================="
echo "GitHub CLI Setup Instructions"
echo "========================================="
echo ""
echo "Step 1: Authenticate with GitHub"
echo "---------------------------------"
echo "Run this command and follow the prompts:"
echo ""
echo "$GH auth login"
echo ""
echo "Choose:"
echo "  - GitHub.com"
echo "  - HTTPS"
echo "  - Yes to authenticate with credentials"
echo "  - Login with a web browser (easier) or paste authentication token"
echo ""
echo "Step 2: Create the repository"
echo "------------------------------"
echo "After authentication, run:"
echo ""
echo "cd '/Users/lokesh/Downloads/Personal web/backend'"
echo "$GH repo create portfolio-backend --public --source=. --remote=origin --push"
echo ""
echo "This will:"
echo "  - Create the repository on GitHub"
echo "  - Set up the remote"
echo "  - Push all your code"
echo ""
echo "========================================="
echo "Quick copy-paste commands:"
echo ""
echo "# Authenticate:"
echo "$GH auth login"
echo ""
echo "# Then create and push:"
echo "cd '/Users/lokesh/Downloads/Personal web/backend' && $GH repo create portfolio-backend --public --source=. --remote=origin --push"
echo "========================================="