#!/bin/bash

echo "========================================="
echo "GitHub Repository Push Instructions"
echo "========================================="
echo ""
echo "Your git repository is ready to push!"
echo ""
echo "Step 1: Create a new repository on GitHub"
echo "----------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: portfolio-backend (or any name you prefer)"
echo "3. Description: Backend API for Lokesh's portfolio drawing wall"
echo "4. Keep it Public or Private (your choice)"
echo "5. DON'T initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "Step 2: Copy and run these commands"
echo "------------------------------------"
echo "After creating the repo, GitHub will show you commands."
echo "Run these commands in your terminal:"
echo ""
echo "cd '/Users/lokesh/Downloads/Personal web/backend'"
echo ""
echo "# If you're using HTTPS (easier):"
echo "git remote add origin https://github.com/YOUR_USERNAME/portfolio-backend.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# OR if you're using SSH (need SSH keys set up):"
echo "git remote add origin git@github.com:YOUR_USERNAME/portfolio-backend.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your GitHub username!"
echo ""
echo "Step 3: Enter your GitHub credentials"
echo "--------------------------------------"
echo "- Username: Your GitHub username"
echo "- Password: Your Personal Access Token (not your password!)"
echo ""
echo "To create a Personal Access Token:"
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Give it a name: 'Portfolio Backend Deploy'"
echo "3. Select scopes: 'repo' (full control)"
echo "4. Click 'Generate token'"
echo "5. Copy the token (you won't see it again!)"
echo "6. Use this token as your password when pushing"
echo ""
echo "========================================="
echo "After pushing, your code will be on GitHub!"
echo "Railway can then auto-deploy from GitHub."
echo "========================================="