#!/bin/bash

echo "==================================="
echo "Local Testing Instructions"
echo "==================================="
echo ""
echo "1. INSTALL DEPENDENCIES:"
echo "   cd backend"
echo "   npm install"
echo ""
echo "2. SET UP LOCAL DATABASE (if you have PostgreSQL installed):"
echo "   Create a .env file with:"
echo "   DATABASE_URL=postgresql://localhost/personal_web_dev"
echo "   PORT=3001"
echo "   NODE_ENV=development"
echo "   ADMIN_KEY=test-admin-key"
echo ""
echo "3. START THE BACKEND:"
echo "   npm start"
echo ""
echo "4. TEST THE API:"
echo "   In another terminal, run these commands:"
echo ""
echo "   # Health check"
echo "   curl http://localhost:3001/health"
echo ""
echo "   # Get marks"
echo "   curl http://localhost:3001/marks"
echo ""
echo "   # Create a pen mark"
echo "   curl -X POST http://localhost:3001/marks \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"type\":\"pen\",\"pts\":[[100,100],[110,110],[120,120]]}'"
echo ""
echo "   # Create a text mark"
echo "   curl -X POST http://localhost:3001/marks \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"type\":\"text\",\"x\":200,\"y\":200,\"text\":\"Hello World\"}'"
echo ""
echo "5. OPEN YOUR WEBSITE:"
echo "   Open Lokesh.dc.html in your browser"
echo "   The drawing feature should now save to the backend!"
echo ""
echo "==================================="